services:
  rabbit:
    image: rabbitmq:4.1-management
    container_name: pie-rabbit
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pie-php
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - rabbit
    command: [ "bash", "-lc", "php -v && composer install --no-interaction" ]
